### ISSUE TITLE
Teacher model selection problem 

### ISSUE THREAD

**Issue by H-cool** [IST-DASLab/SparseFinetuning#1]
Teacher model selection problem

Hello, I would like to ask whether the teacher model you use in the knowledge distillation process is an unpruned model or a model with a more complex network structure

**Comment by eldarkurtic** [comment]
It is an unpruned model which is first fine-tuned on the target dataset. For example:
1. Take a pretrained MPT-7b model
2. Finetune it on GSM8k
3. Use it as the teacher for sparse finetuning
