### ISSUE TITLE
llama error

### ISSUE THREAD

**Issue by H-cool** [IST-DASLab/SparseFinetuning#4]
Hello, I see that your paper is still being tested on the llama model later, but transformer>4.32.0 is required to import the llama series models, and the code requires transformer<4.32.0. I got an error during the import of the llama model. Could you please share the code you fine-tuned on llama? Thank you so much

**Comment by H-cool** [comment]
The error part shows that there is a problem with the model import part, and the rotary_emb.inv_freq layer was initialized because it could not be imported.

**Comment by eldarkurtic** [comment]
You can safely increase the transformer version (I think it won't break anything). Notice that you might want to adapt some parts for saving of the model in the `train_sparse.py` script, as in the current form it is hardcoded for MPT models. 

Regarding `rotary_emb.inv_freq`: this is okay, as this is going to be initialized from scratch. No need to load anything.
